#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'key-teleop','console_scripts','key_teleop'
__requires__ = 'key-teleop'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('key-teleop', 'console_scripts', 'key_teleop')()
    )
