#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'twist-to-ackermann','console_scripts','twist_to_ackermann_node'
__requires__ = 'twist-to-ackermann'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('twist-to-ackermann', 'console_scripts', 'twist_to_ackermann_node')()
    )
