#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'f1tenth-stack','console_scripts','tf_publisher'
__requires__ = 'f1tenth-stack'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('f1tenth-stack', 'console_scripts', 'tf_publisher')()
    )
